name: lost_and_found_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  google_fonts: ^6.1.0  # ✅ Added Google Fonts for futuristic UI
  firebase_auth: ^5.6.0
  fluttertoast: ^8.2.12
  cloud_firestore: ^5.6.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/crumbled paper.jpg

  # No need for manual font imports because we're using Google Fonts
