// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU-yatKsPB5SaSdc5ZyRR-AxvT4i0tcGs',
    appId: '1:865840769017:web:4cf9fdd4465a3cf63f7f28',
    messagingSenderId: '865840769017',
    projectId: 'foundit-35559',
    authDomain: 'foundit-35559.firebaseapp.com',
    storageBucket: 'foundit-35559.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxtRYmvNFOqO5VTDqbzn0cPOSJl556e8I',
    appId: '1:865840769017:android:36e382b3ae7a95dc3f7f28',
    messagingSenderId: '865840769017',
    projectId: 'foundit-35559',
    storageBucket: 'foundit-35559.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTQqPfaGV1QLva-EaB5rYDTbV5CNbirAw',
    appId: '1:865840769017:ios:0b65ebec055c33f23f7f28',
    messagingSenderId: '865840769017',
    projectId: 'foundit-35559',
    storageBucket: 'foundit-35559.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTQqPfaGV1QLva-EaB5rYDTbV5CNbirAw',
    appId: '1:865840769017:ios:0b65ebec055c33f23f7f28',
    messagingSenderId: '865840769017',
    projectId: 'foundit-35559',
    storageBucket: 'foundit-35559.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU-yatKsPB5SaSdc5ZyRR-AxvT4i0tcGs',
    appId: '1:865840769017:web:0d7b5a5b65037b963f7f28',
    messagingSenderId: '865840769017',
    projectId: 'foundit-35559',
    authDomain: 'foundit-35559.firebaseapp.com',
    storageBucket: 'foundit-35559.firebasestorage.app',
  );
}
